package fr.n7.fut.model.players;

public enum League {
	DEN1 { @Override public String toString() { return "Alka Superliga"; } },
	SWE1 { @Override public String toString() { return "Allsvenskan"; } },
	GER1 { @Override public String toString() { return "Bundesliga"; } },
	ITA1 { @Override public String toString() { return "Calcio A"; } },
	CHI1 { @Override public String toString() { return "Camp. Scotiabank"; } },
	CZE1 { @Override public String toString() { return "Ceska Liga"; } },
	SAU1 { @Override public String toString() { return "Dawry Jameel"; } },
	POL1 { @Override public String toString() { return "Ekstraklasa"; } },
	NOR1 { @Override public String toString() { return "Eliteserien"; } },
	NED1 { @Override public String toString() { return "Eredivisie"; } },
	FIN1 { @Override public String toString() { return "Finnliiga"; } },
	GRE1 { @Override public String toString() { return "Hellas Liga"; } },
	AUS1 { @Override public String toString() { return "Hyundai A-League"; } },
	KOR1 { @Override public String toString() { return "K LEAGUE Classic"; } },
	ESP1 { @Override public String toString() { return "LaLiga Santander"; } },
	MEX1 { @Override public String toString() { return "LIGA Bancomer MX"; } },
	COL1 { @Override public String toString() { return "Liga Dimayor"; } },
	BRA1 { @Override public String toString() { return "Liga do Brasil"; } },
	POR1 { @Override public String toString() { return "Liga NOS"; } },
	FRA1 { @Override public String toString() { return "Ligue 1 Conforama"; } },
	JPN1 { @Override public String toString() { return "Meiji Yasuda J1"; } },
	USA1 { @Override public String toString() { return "MLS"; } },
	AUT1 { @Override public String toString() { return "O. Bundesliga"; } },
	ENG1 { @Override public String toString() { return "Premier League"; } },
	ARG1 { @Override public String toString() { return "Primera Division"; } },
	BEL1 { @Override public String toString() { return "Pro League"; } },
	SUI1 { @Override public String toString() { return "RSL"; } },
	RUS1 { @Override public String toString() { return "Russian League"; } },
	SCO1 { @Override public String toString() { return "Scottish Prem"; } },
	RSA1 { @Override public String toString() { return "South African FL"; } },
	IRL1 { @Override public String toString() { return "SSE Airtricity Lge"; } },
	TUR1 { @Override public String toString() { return "Süper Lig"; } },
	UKR1 { @Override public String toString() { return "Ukrayina Lih"; } }
}
