package fr.n7.fut.model.players;

public enum Nation {
	AFG { @Override public String toString() { return "Afghanistan"; } },
	ALB { @Override public String toString() { return "Albania"; } },
	ALG { @Override public String toString() { return "Algeria"; } },
	ASA { @Override public String toString() { return "American Samoa"; } },
	AND { @Override public String toString() { return "Andorra"; } },
	ANG { @Override public String toString() { return "Angola"; } },
	AIA { @Override public String toString() { return "Anguilla"; } },
	ATG { @Override public String toString() { return "Antigua and Barbuda"; } },
	ARG { @Override public String toString() { return "Argentina"; } },
	ARM { @Override public String toString() { return "Armenia"; } },
	ARU { @Override public String toString() { return "Aruba"; } },
	AUS { @Override public String toString() { return "Australia"; } },
	AUT { @Override public String toString() { return "Austria"; } },
	AZE { @Override public String toString() { return "Azerbaijan"; } },
	BAH { @Override public String toString() { return "Bahamas"; } },
	BHR { @Override public String toString() { return "Bahrain"; } },
	BAN { @Override public String toString() { return "Bangladesh"; } },
	BRB { @Override public String toString() { return "Barbados"; } },
	BLR { @Override public String toString() { return "Belarus"; } },
	BEL { @Override public String toString() { return "Belgium"; } },
	BLZ { @Override public String toString() { return "Belize"; } },
	BEN { @Override public String toString() { return "Benin"; } },
	BER { @Override public String toString() { return "Bermuda"; } },
	BHU { @Override public String toString() { return "Bhutan"; } },
	BOL { @Override public String toString() { return "Bolivia"; } },
	BIH { @Override public String toString() { return "Bosnia and Herzegovina"; } },
	BOT { @Override public String toString() { return "Botswana"; } },
	BRA { @Override public String toString() { return "Brazil"; } },
	VGB { @Override public String toString() { return "British Virgin Islands"; } },
	BRU { @Override public String toString() { return "Brunei"; } },
	BUL { @Override public String toString() { return "Bulgaria"; } },
	BFA { @Override public String toString() { return "Burkina Faso"; } },
	BDI { @Override public String toString() { return "Burundi"; } },
	CAM { @Override public String toString() { return "Cambodia"; } },
	CMR { @Override public String toString() { return "Cameroon"; } },
	CAN { @Override public String toString() { return "Canada"; } },
	CPV { @Override public String toString() { return "Cape Verde"; } },
	CAY { @Override public String toString() { return "Cayman Islands"; } },
	CTA { @Override public String toString() { return "Central African Republic"; } },
	CHA { @Override public String toString() { return "Chad"; } },
	CHI { @Override public String toString() { return "Chile"; } },
	CHN { @Override public String toString() { return "China PR"; } },
	TPE { @Override public String toString() { return "Chinese Taipei"; } },
	COL { @Override public String toString() { return "Colombia"; } },
	COM { @Override public String toString() { return "Comoros"; } },
	CGO { @Override public String toString() { return "Congo"; } },
	COK { @Override public String toString() { return "Cook Islands"; } },
	CRC { @Override public String toString() { return "Costa Rica"; } },
	CRO { @Override public String toString() { return "Croatia"; } },
	CUB { @Override public String toString() { return "Cuba"; } },
	CUW { @Override public String toString() { return "Curaçao"; } },
	CYP { @Override public String toString() { return "Cyprus"; } },
	CZE { @Override public String toString() { return "Czech Republic"; } },
	DEN { @Override public String toString() { return "Denmark"; } },
	DJI { @Override public String toString() { return "Djibouti"; } },
	DMA { @Override public String toString() { return "Dominica"; } },
	DOM { @Override public String toString() { return "Dominican Republic"; } },
	COD { @Override public String toString() { return "DR Congo"; } },
	ECU { @Override public String toString() { return "Ecuador"; } },
	EGY { @Override public String toString() { return "Egypt"; } },
	SLV { @Override public String toString() { return "El Salvador"; } },
	ENG { @Override public String toString() { return "England"; } },
	EQG { @Override public String toString() { return "Equatorial Guinea"; } },
	ERI { @Override public String toString() { return "Eritrea"; } },
	EST { @Override public String toString() { return "Estonia"; } },
	ETH { @Override public String toString() { return "Ethiopia"; } },
	FRO { @Override public String toString() { return "Faroe Islands"; } },
	FIJ { @Override public String toString() { return "Fiji"; } },
	FIN { @Override public String toString() { return "Finland"; } },
	FRA { @Override public String toString() { return "France"; } },
	GAB { @Override public String toString() { return "Gabon"; } },
	GAM { @Override public String toString() { return "Gambia"; } },
	GEO { @Override public String toString() { return "Georgia"; } },
	GER { @Override public String toString() { return "Germany"; } },
	GHA { @Override public String toString() { return "Ghana"; } },
	GIB { @Override public String toString() { return "Gibraltar"; } },
	GRE { @Override public String toString() { return "Greece"; } },
	GRN { @Override public String toString() { return "Grenada"; } },
	GUM { @Override public String toString() { return "Guam"; } },
	GUA { @Override public String toString() { return "Guatemala"; } },
	GUI { @Override public String toString() { return "Guinea"; } },
	GNB { @Override public String toString() { return "Guinea-Bissau"; } },
	GUY { @Override public String toString() { return "Guyana"; } },
	HAI { @Override public String toString() { return "Haiti"; } },
	HON { @Override public String toString() { return "Honduras"; } },
	HKG { @Override public String toString() { return "Hong Kong"; } },
	HUN { @Override public String toString() { return "Hungary"; } },
	ISL { @Override public String toString() { return "Iceland"; } },
	IND { @Override public String toString() { return "India"; } },
	IDN { @Override public String toString() { return "Indonesia"; } },
	IRN { @Override public String toString() { return "Iran"; } },
	IRQ { @Override public String toString() { return "Iraq"; } },
	ISR { @Override public String toString() { return "Israel"; } },
	ITA { @Override public String toString() { return "Italy"; } },
	CIV { @Override public String toString() { return "Ivory Coast"; } },
	JAM { @Override public String toString() { return "Jamaica"; } },
	JPN { @Override public String toString() { return "Japan"; } },
	JOR { @Override public String toString() { return "Jordan"; } },
	KAZ { @Override public String toString() { return "Kazakhstan"; } },
	KEN { @Override public String toString() { return "Kenya"; } },
	KVX { @Override public String toString() { return "Kosovo"; } },
	KUW { @Override public String toString() { return "Kuwait"; } },
	KGZ { @Override public String toString() { return "Kyrgyzstan"; } },
	LAO { @Override public String toString() { return "Laos"; } },
	LVA { @Override public String toString() { return "Latvia"; } },
	LIB { @Override public String toString() { return "Lebanon"; } },
	LES { @Override public String toString() { return "Lesotho"; } },
	LBR { @Override public String toString() { return "Liberia"; } },
	LBY { @Override public String toString() { return "Libya"; } },
	LIE { @Override public String toString() { return "Liechtenstein"; } },
	LTU { @Override public String toString() { return "Lithuania"; } },
	LUX { @Override public String toString() { return "Luxembourg"; } },
	MAC { @Override public String toString() { return "Macau"; } },
	MKD { @Override public String toString() { return "Macedonia"; } },
	MAD { @Override public String toString() { return "Madagascar"; } },
	MWI { @Override public String toString() { return "Malawi"; } },
	MAS { @Override public String toString() { return "Malaysia"; } },
	MDV { @Override public String toString() { return "Maldives"; } },
	MLI { @Override public String toString() { return "Mali"; } },
	MLT { @Override public String toString() { return "Malta"; } },
	MTN { @Override public String toString() { return "Mauritania"; } },
	MRI { @Override public String toString() { return "Mauritius"; } },
	MEX { @Override public String toString() { return "Mexico"; } },
	MDA { @Override public String toString() { return "Moldova"; } },
	MNG { @Override public String toString() { return "Mongolia"; } },
	MNE { @Override public String toString() { return "Montenegro"; } },
	MSR { @Override public String toString() { return "Montserrat"; } },
	MAR { @Override public String toString() { return "Morocco"; } },
	MOZ { @Override public String toString() { return "Mozambique"; } },
	MYA { @Override public String toString() { return "Myanmar"; } },
	NAM { @Override public String toString() { return "Namibia"; } },
	NEP { @Override public String toString() { return "Nepal"; } },
	NED { @Override public String toString() { return "Netherlands"; } },
	NCL { @Override public String toString() { return "New Caledonia"; } },
	NZL { @Override public String toString() { return "New Zealand"; } },
	NCA { @Override public String toString() { return "Nicaragua"; } },
	NIG { @Override public String toString() { return "Niger"; } },
	NGA { @Override public String toString() { return "Nigeria"; } },
	PRK { @Override public String toString() { return "North Korea"; } },
	NIR { @Override public String toString() { return "Northern Ireland"; } },
	NOR { @Override public String toString() { return "Norway"; } },
	OMA { @Override public String toString() { return "Oman"; } },
	PAK { @Override public String toString() { return "Pakistan"; } },
	PLE { @Override public String toString() { return "Palestine"; } },
	PAN { @Override public String toString() { return "Panama"; } },
	PNG { @Override public String toString() { return "Papua New Guinea"; } },
	PAR { @Override public String toString() { return "Paraguay"; } },
	PER { @Override public String toString() { return "Peru"; } },
	PHI { @Override public String toString() { return "Philippines"; } },
	POL { @Override public String toString() { return "Poland"; } },
	POR { @Override public String toString() { return "Portugal"; } },
	PUR { @Override public String toString() { return "Puerto Rico"; } },
	QAT { @Override public String toString() { return "Qatar"; } },
	IRL { @Override public String toString() { return "Republic of Ireland"; } },
	ROU { @Override public String toString() { return "Romania"; } },
	RUS { @Override public String toString() { return "Russia"; } },
	RWA { @Override public String toString() { return "Rwanda"; } },
	SKN { @Override public String toString() { return "Saint Kitts and Nevis"; } },
	LCA { @Override public String toString() { return "Saint Lucia"; } },
	VIN { @Override public String toString() { return "Saint Vincent and the Grenadines"; } },
	SAM { @Override public String toString() { return "Samoa"; } },
	SMR { @Override public String toString() { return "San Marino"; } },
	STP { @Override public String toString() { return "São Tomé and Príncipe"; } },
	KSA { @Override public String toString() { return "Saudi Arabia"; } },
	SCO { @Override public String toString() { return "Scotland"; } },
	SEN { @Override public String toString() { return "Senegal"; } },
	SRB { @Override public String toString() { return "Serbia"; } },
	SEY { @Override public String toString() { return "Seychelles"; } },
	SLE { @Override public String toString() { return "Sierra Leone"; } },
	SIN { @Override public String toString() { return "Singapore"; } },
	SVK { @Override public String toString() { return "Slovakia"; } },
	SVN { @Override public String toString() { return "Slovenia"; } },
	SOL { @Override public String toString() { return "Solomon Islands"; } },
	SOM { @Override public String toString() { return "Somalia"; } },
	RSA { @Override public String toString() { return "South Africa"; } },
	KOR { @Override public String toString() { return "South Korea"; } },
	SSD { @Override public String toString() { return "South Sudan"; } },
	ESP { @Override public String toString() { return "Spain"; } },
	SRI { @Override public String toString() { return "Sri Lanka"; } },
	SDN { @Override public String toString() { return "Sudan"; } },
	SUR { @Override public String toString() { return "Suriname"; } },
	SWZ { @Override public String toString() { return "Swaziland"; } },
	SWE { @Override public String toString() { return "Sweden"; } },
	SUI { @Override public String toString() { return "Switzerland"; } },
	SYR { @Override public String toString() { return "Syria"; } },
	TAH { @Override public String toString() { return "Tahiti"; } },
	TJK { @Override public String toString() { return "Tajikistan"; } },
	TAN { @Override public String toString() { return "Tanzania"; } },
	THA { @Override public String toString() { return "Thailand"; } },
	TLS { @Override public String toString() { return "Timor-Leste"; } },
	TOG { @Override public String toString() { return "Togo"; } },
	TGA { @Override public String toString() { return "Tonga"; } },
	TRI { @Override public String toString() { return "Trinidad and Tobago"; } },
	TUN { @Override public String toString() { return "Tunisia"; } },
	TUR { @Override public String toString() { return "Turkey"; } },
	TKM { @Override public String toString() { return "Turkmenistan"; } },
	TCA { @Override public String toString() { return "Turks and Caicos Islands"; } },
	UGA { @Override public String toString() { return "Uganda"; } },
	UKR { @Override public String toString() { return "Ukraine"; } },
	UAE { @Override public String toString() { return "United Arab Emirates"; } },
	USA { @Override public String toString() { return "United States"; } },
	URU { @Override public String toString() { return "Uruguay"; } },
	VIR { @Override public String toString() { return "U.S. Virgin Islands"; } },
	UZB { @Override public String toString() { return "Uzbekistan"; } },
	VAN { @Override public String toString() { return "Vanuatu"; } },
	VEN { @Override public String toString() { return "Venezuela"; } },
	VIE { @Override public String toString() { return "Vietnam"; } },
	WAL { @Override public String toString() { return "Wales"; } },
	YEM { @Override public String toString() { return "Yemen"; } },
	ZAM { @Override public String toString() { return "Zambia"; } },
	ZIM { @Override public String toString() { return "Zimbabwe"; } }
}
